// The catalog she starts with. Written into storage the first time the panel or the
// site asks for items, so everything on the site is editable at /admin from day one.
// After that this file is never consulted again: her edits are the truth.

export const SEED = [
  {"img": "/assets/bottle-lions-pink.jpg", "desc": "Detroit Lions water bottle. Pink and blue One Pride wrap with a flip handle lid."},
  {"img": "/assets/socks-lions-name.jpg", "desc": "Personalized Detroit Lions socks. Your name printed at the bottom in pink and blue."},
  {"img": "/assets/socks-lions-paws.jpg", "desc": "Detroit Lions One Pride socks. Paw prints down the leg in blue and silver."},
  {"img": "/assets/socks-lions-classic.jpg", "desc": "Detroit Lions socks. Team logo and paw prints on soft white crew socks."},
  {"img": "/assets/socks-spartans.jpg", "desc": "Michigan State Spartans socks. Go Green Go White on one, Spartan Nation on the other."},
  {"img": "/assets/keychains-lions.jpg", "desc": "Detroit Lions wristlet keychains. Five designs, from One Pride to Same City Same Pride."},
  {"img": "/assets/keychains-pistons.jpg", "desc": "Detroit Pistons wristlet keychains. Five designs, Bad Boys Mentality to Hoops Culture."},
  {"img": "/assets/keychain-butterfly.jpg", "desc": "Butterfly wristlet keychain. Pink and purple butterflies and hearts on a soft strap."},
  {"img": "/assets/keychain-pink-ribbon.jpg", "desc": "Breast cancer awareness wristlet. Faith Hope Love Fight on one side, Stronger Than Cancer on the other."},
  {"img": "/assets/chapstick-holders.jpg", "desc": "Personalized chapstick holders. Names, quotes, teams and themes, clipped right to your keys."},
  {"img": "/assets/chapstick-lions.jpg", "desc": "Detroit Lions chapstick holder. Clips to your keys or bag and fits most lip balms."},
  {"img": "/assets/chapstick-pink-ribbon.jpg", "desc": "Pink ribbon chapstick holder. Together We Are Stronger, in soft pink."},
  {"img": "/assets/chapstick-floral.jpg", "desc": "Chapstick holder with pink flowers. Small, sturdy, and easy to find in your bag."},
  {"img": "/assets/chapstick-bows.jpg", "desc": "Chapstick holder with bows and smileys. A little gift that gets used every day."},
  {"img": "/assets/flask-name-glitter.jpg", "desc": "Personalized glitter flask. Your name in pink and purple sparkle with butterflies and a crown."},
  {"img": "/assets/flask-lions-onepride.jpg", "desc": "Detroit Lions flask. Stainless steel with a One Pride wrap."},
  {"img": "/assets/flask-lions-spartans.jpg", "desc": "Lions and Spartans flask. Both logos, split down the middle, for a house divided."},
  {"img": "/assets/flask-lions-spartans-mascots.jpg", "desc": "Lions and Spartans mascot flask. Different teams, same heart."},
  {"img": "/assets/glass-lions-nation.jpg", "desc": "Detroit Lions pint glass. Lions Nation, good drinks and better games."},
  {"img": "/assets/glass-she-said-yes.jpg", "desc": "She Said Yes glass. Frosted glass with a ring and hearts for the engagement party."},
  {"img": "/assets/glass-just-married.jpg", "desc": "Just Married glass. Rings, hearts, and sparkle, a keepsake from the day."},
  {"img": "/assets/shotglass-name-tall.jpg", "desc": "Personalized tall shot glass. Your name with butterflies and a crown on frosted glass."},
  {"img": "/assets/shotglass-photo.jpg", "desc": "Photo shot glass. Your favorite picture and a name on frosted glass."},
  {"img": "/assets/coaster-photo-buddies.jpg", "desc": "Photo coaster. Your picture printed edge to edge with a name and a message."},
  {"img": "/assets/coaster-photo-name.jpg", "desc": "Personalized photo coaster. A portrait, a name, and words that mean something."},
  {"img": "/assets/mousepad-lions-skyline.jpg", "desc": "Detroit Lions mouse pad. The skyline and the logo, One Pride One Detroit."},
  {"img": "/assets/mousepad-lions.jpg", "desc": "Detroit Lions mouse pad. Classic logo on blue and silver."},
  {"img": "/assets/ornament-name.jpg", "desc": "Personalized Christmas ornament. Your name and the year in a wreath with a red bow."},
  {"img": "/assets/ornament-family.jpg", "desc": "Family Christmas ornament. Your family name and the year, ready to hang."},
  {"img": "/assets/ornament-pink-ribbon.jpg", "desc": "Pink ribbon ornament. Faith, hope, strength, survive, in honor of all those who fight."},
  {"img": "/assets/bag-lions.jpg", "desc": "Detroit Lions drawstring bag. Team logo on a soft white bag with black cords."},
  {"img": "/assets/bag-beat-cancer.jpg", "desc": "Beat Cancer drawstring bag. Pink ribbon and butterflies, light enough for every day."},
  {"img": "/assets/bag-logo.jpg", "desc": "Custom drawstring bag. Your logo, your business, or your team, printed full size."},
  {"img": "/assets/pouch-name-canvas.jpg", "desc": "Personalized canvas wristlet. Your name on a zip pouch with a matching wrist strap."},
  {"img": "/assets/fan-lions.jpg", "desc": "Detroit Lions folding fan. Pops open for the game and folds back into its own pouch."},
  {"img": "/assets/fan-pink-ribbon.jpg", "desc": "Pink ribbon folding fan. Opens flat, folds away, easy to carry."},
  {"img": "/assets/tumbler-pair.jpg", "desc": "Adult Tumbler, 20 oz. Keeps drinks hot or cold. Personalized just for you."},
  {"img": "/assets/set-pawpatrol.jpg", "desc": "Youth Tumbler, 15 oz. Sized for older kids, built for everyday use."},
  {"img": "/assets/set-sets.jpg", "desc": "Kids Water Bottle, 12 oz. Flip-top lid, names and favorite themes."},
  {"img": "/assets/mug-real.jpg", "desc": "Custom Mug, 11 & 15 oz. Personalized coffee mug for any occasion."},
  {"img": "/assets/photo-tumbler.jpg", "desc": "Coffee Tumbler, 12 oz. Clear slide lid. Turn your moments into a daily reminder."},
  {"img": "/assets/hero-kingofpop.jpg", "desc": "Photo Tumblers. Full wrap with your favorite family pictures."},
  {"img": "/assets/set-sets.jpg", "desc": "Matching Back-to-School Set. Personalized lunch bag, pencil bag and tumbler, in any theme."},
  {"img": "/assets/puzzle.jpg", "desc": "Heart Puzzle, 75 pc. Turn your memories into pieces of love. Carrying box included."},
  {"img": "/assets/mirror.jpg", "desc": "Pocket Mirrors & Buttons. Compact, perfect for on the go, a lovely little gift."},
  {"img": "/assets/apron.jpg", "desc": "Aprons & Stylist Smocks. Cook. Create. Love. Add your name or business logo."},
  {"img": "/assets/money-bouquet.jpg", "desc": "Money Bouquet. A cash gift arranged like a flower bouquet."}
];
